/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 完整健康检查
         * @description 检查数据库、内存和磁盘健康状态，用于生产环境监控
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询审计日志列表 */
        get: operations["AuditLogController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有 todos */
        get: operations["TodoController_findAll"];
        put?: never;
        /** 创建新 todo */
        post: operations["TodoController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 ID 获取 todo */
        get: operations["TodoController_findById"];
        put?: never;
        post?: never;
        /** 删除 todo */
        delete: operations["TodoController_delete"];
        options?: never;
        head?: never;
        /** 更新 todo */
        patch: operations["TodoController_update"];
        trace?: never;
    };
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建草稿文章 */
        post: operations["ArticleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 发布文章 */
        patch: operations["ArticleController_publish"];
        trace?: never;
    };
    "/api/articles/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 归档文章 */
        patch: operations["ArticleController_archive"];
        trace?: never;
    };
    "/api/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 ID 获取文章详情 */
        get: operations["ArticleController_findById"];
        /** 更新文章内容（仅草稿状态可编辑） */
        put: operations["ArticleController_update"];
        post?: never;
        /** 删除文章 */
        delete: operations["ArticleController_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 为文章添加标签 */
        post: operations["ArticleController_addTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}/tags/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 移除文章标签 */
        delete: operations["ArticleController_removeTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取全部文章列表（无分页，适用于数据量小的全量获取场景） */
        get: operations["ArticleController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/paginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取文章列表（偏移分页，默认推荐方式） */
        get: operations["ArticleController_findPaginated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取文章列表（游标分页，适用于大数据集或实时数据场景） */
        get: operations["ArticleController_findCursor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据 Slug 获取文章 */
        get: operations["ArticleController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户注册 */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新访问令牌
         * @description 使用 Refresh Token 获取新的 Access Token（同时轮换 Refresh Token）
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前会话信息 */
        get: operations["AuthController_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取会话列表 */
        get: operations["AuthController_listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出（单设备） */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销指定会话 */
        post: operations["AuthController_revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销所有会话 */
        post: operations["AuthController_revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户列表 */
        get: operations["UserController_findAll"];
        put?: never;
        /** 创建用户 */
        post: operations["UserController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户详情 */
        get: operations["UserController_findById"];
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: operations["UserController_delete"];
        options?: never;
        head?: never;
        /** 更新用户 */
        patch: operations["UserController_update"];
        trace?: never;
    };
    "/api/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 分配用户角色（仅 ADMIN） */
        put: operations["UserController_assignRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取仪表盘统计数据 */
        get: operations["DashboardController_getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 创建订单（幂等） */
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 确认支付（乐观锁） */
        patch: operations["OrderController_pay"];
        trace?: never;
    };
    "/api/orders/{id}/ship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起发货（异步） */
        post: operations["OrderController_ship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/bulk-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 批量取消订单（207 Multi-Status） */
        delete: operations["OrderController_bulkCancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取订单详情（响应含 ETag） */
        get: operations["OrderController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询异步任务状态 */
        get: operations["JobController_findById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditLogResponseDto: {
            id: string;
            action: string;
            actorId: string | null;
            actorEmail: string | null;
            resourceType: string | null;
            resourceId: string | null;
            detail: Record<string, never>;
            ipAddress: string | null;
            userAgent: string | null;
            requestId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["AuditLogResponseDto"][];
            /**
             * @description 当前页码（从 1 开始）
             * @example 1
             */
            page: number;
            /**
             * @description 每页数量
             * @example 20
             */
            pageSize: number;
            /**
             * @description 总项数
             * @example 100
             */
            total: number;
            /**
             * @description 是否有更多数据
             * @example true
             */
            hasMore: boolean;
        };
        TodoResponseDto: {
            id: string;
            title: string;
            description: string | null;
            isCompleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TodoListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["TodoResponseDto"][];
        };
        CreateTodoDto: {
            title: string;
            description?: string;
            isCompleted?: boolean;
        };
        UpdateTodoDto: {
            title?: string;
            description?: string;
            isCompleted?: boolean;
        };
        CreateArticleDto: {
            /**
             * @example tech
             * @enum {string}
             */
            category?: "tech" | "design" | "product" | "other";
            title: string;
            content: string;
            author?: string;
            isPinned?: boolean;
        };
        ArticleResponseDto: {
            /**
             * @example draft
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /**
             * @example tech
             * @enum {string}
             */
            category: "tech" | "design" | "product" | "other";
            id: string;
            title: string;
            content: string;
            slug: string;
            tags: string[];
            author: string;
            viewCount: number;
            isPinned: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        UpdateArticleDto: {
            /**
             * @example tech
             * @enum {string}
             */
            category?: "tech" | "design" | "product" | "other";
            title?: string;
            content?: string;
            author?: string;
            isPinned?: boolean;
        };
        AddTagDto: {
            tag: string;
        };
        ArticleAllListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["ArticleResponseDto"][];
        };
        ArticleListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["ArticleResponseDto"][];
            /**
             * @description 当前页码（从 1 开始）
             * @example 1
             */
            page: number;
            /**
             * @description 每页数量
             * @example 20
             */
            pageSize: number;
            /**
             * @description 总项数
             * @example 100
             */
            total: number;
            /**
             * @description 是否有更多数据
             * @example true
             */
            hasMore: boolean;
        };
        ArticleCursorListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["ArticleResponseDto"][];
            /**
             * @description 下一页游标令牌（Base64 编码），无更多数据时为 null
             * @example eyJpZCI6InVzcl8wMjAifQ==
             */
            nextCursor: Record<string, never> | null;
            /**
             * @description 是否有更多数据
             * @example true
             */
            hasMore: boolean;
        };
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /**
             * @description 3-30个字符，只能包含字母、数字、下划线和连字符
             * @example john_doe
             */
            name: string;
            /**
             * @description 至少8个字符，必须包含字母和数字
             * @example Pass123456
             */
            password: string;
        };
        UserInfo: {
            id: string;
            email: string;
            role: string | null;
        };
        LoginResponseDto: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["UserInfo"];
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example Pass123456 */
            password: string;
        };
        RefreshTokenDto: {
            /**
             * Format: uuid
             * @description 登录时返回的 Refresh Token
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            refreshToken: string;
        };
        RefreshTokenResponseDto: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["UserInfo"];
        };
        SessionUserDto: {
            id: string;
            email: string;
            role: string | null;
        };
        SessionInfoDto: {
            id: string;
            /** Format: date-time */
            expiresAt: string;
            ipAddress: string | null;
            userAgent: string | null;
        };
        SessionResponseDto: {
            user: components["schemas"]["SessionUserDto"];
            session: components["schemas"]["SessionInfoDto"];
        };
        SessionItemDto: {
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            ipAddress: string | null;
            userAgent: string | null;
            isCurrent: boolean;
        };
        SessionsListResponseDto: {
            sessions: components["schemas"]["SessionItemDto"][];
        };
        LogoutDto: {
            /** @description Refresh Token */
            refreshToken: string;
        };
        LogoutResponseDto: {
            /** @description 是否成功 */
            success: boolean;
            /** @description 消息 */
            message: string;
        };
        RevokeSessionDto: {
            /** Format: uuid */
            sessionId: string;
        };
        RevokeSessionResponseDto: {
            success: boolean;
            message: string;
        };
        LogoutAllResponseDto: {
            /** @description 撤销的会话数量 */
            revokedCount: number;
            /** @description 消息 */
            message: string;
        };
        UserResponseDto: {
            id: string;
            name: string;
            displayName: string | null;
            email: string;
            emailVerified: boolean;
            image: string | null;
            role: string | null;
            banned: boolean;
            banReason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserListResponseDto: {
            /**
             * @description 对象类型标识符
             * @default list
             * @example list
             * @enum {string}
             */
            object: "list";
            /** @description 实际数据数组 */
            data: components["schemas"]["UserResponseDto"][];
            /**
             * @description 当前页码（从 1 开始）
             * @example 1
             */
            page: number;
            /**
             * @description 每页数量
             * @example 20
             */
            pageSize: number;
            /**
             * @description 总项数
             * @example 100
             */
            total: number;
            /**
             * @description 是否有更多数据
             * @example true
             */
            hasMore: boolean;
        };
        CreateUserDto: {
            name?: string;
            displayName?: string;
            email: string;
            password: string;
            role?: string;
        };
        UpdateUserDto: {
            name?: string;
            displayName?: string;
            banned?: boolean;
            banReason?: string;
        };
        AssignRoleDto: {
            /**
             * @example USER
             * @enum {string}
             */
            role: "ADMIN" | "USER" | "EDITOR" | "MODERATOR";
        };
        StatisticsDto: {
            totalUsers: number;
            activeUsers: number;
            adminUsers: number;
            newUsersToday: number;
        };
        OrderItemDto: {
            productId: string;
            quantity: number;
            /** @description 字符串类型保证精度安全 */
            unitPrice: string;
        };
        CreateOrderDto: {
            userId: string;
            items: components["schemas"]["OrderItemDto"][];
            currency?: string;
        };
        OrderItemResponseDto: {
            productId: string;
            quantity: number;
            unitPrice: string;
        };
        OrderResponseDto: {
            /** @enum {string} */
            status: "pending_payment" | "paid" | "shipping" | "completed" | "cancelled";
            id: string;
            userId: string;
            items: components["schemas"]["OrderItemResponseDto"][];
            totalAmount: string;
            currency: string;
            /** @description 乐观锁版本号（用于 ETag） */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ShipOrderResponseDto: {
            jobId: string;
        };
        BulkCancelDto: {
            ids: string[];
        };
        BulkCancelItemResponseDto: {
            /** @example 204 */
            status: number;
            id: string;
            error?: {
                code: string;
                message: string;
            };
        };
        BulkCancelResponseDto: {
            object: string;
            data: components["schemas"]["BulkCancelItemResponseDto"][];
            summary: {
                succeeded: number;
                failed: number;
            };
        };
        JobResponseDto: {
            id: string;
            type: string;
            status: Record<string, never>;
            payload: Record<string, never>;
            /** @description 任务完成后填充 */
            result: Record<string, never>;
            error: {
                code: string;
                message: string;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProblemDetailsDto: {
            /**
             * @description 问题类型 URI，应可解引用到人类可读文档
             * @example https://api.example.com/errors/validation-failed
             */
            type: string;
            /**
             * @description 简短的人类可读摘要
             * @example 请求验证失败
             */
            title: string;
            /**
             * @description HTTP 状态码
             * @example 422
             */
            status: number;
            /**
             * @description 问题发生的 URI 引用
             * @example /api/users
             */
            instance?: string;
            /**
             * @description 请求追踪 ID
             * @example req_xyz789
             */
            request_id?: string;
            /**
             * @description 关联 ID（业务事务追踪）
             * @example corr_shop_session_abc123
             */
            correlation_id?: string;
            /**
             * @description 分布式追踪 ID（W3C Trace Context）
             * @example 4bf92f3577b34da6a3ce929d0e0e4736
             */
            trace_id?: string;
            /**
             * @description 错误发生时间（ISO 8601格式）
             * @example 2024-11-03T10:30:00Z
             */
            timestamp?: string;
            /**
             * @description 错误详情数组（所有错误信息的唯一来源，有 field 表示字段错误，无 field 表示通用错误）
             * @example [
             *       {
             *         "field": "email",
             *         "pointer": "/email",
             *         "code": "INVALID_EMAIL",
             *         "message": "邮箱格式不正确"
             *       }
             *     ]
             */
            errors: Record<string, never>[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuditLogController_findAll: {
        parameters: {
            query?: {
                /** @description 按操作人 ID 筛选 */
                actorId?: string;
                /** @description 按操作类型筛选 */
                action?: string;
                /** @description 页码（从1开始） */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功返回 todos 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoDto"];
            };
        };
        responses: {
            /** @description 成功创建 todo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description 验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功返回 todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功删除 todo */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    TodoController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoDto"];
            };
        };
        responses: {
            /** @description 成功更新 todo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoResponseDto"];
                };
            };
            /** @description Todo 不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 验证失败 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateArticleDto"];
            };
        };
        responses: {
            /** @description 创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 请求参数错误 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发布成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如内容不足 50 字） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 归档成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如文章未发布） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateArticleDto"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如文章已发布） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_addTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagDto"];
            };
        };
        responses: {
            /** @description 添加成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 业务规则错误（如超过标签数量限制） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_removeTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 ID */
                id: string;
                /** @description 标签名称 */
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 移除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleAllListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findPaginated: {
        parameters: {
            query?: {
                /** @description 页码（从1开始） */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findCursor: {
        parameters: {
            query?: {
                /** @description 每页数量 */
                pageSize?: number;
                /** @description 游标令牌（Base64编码的JSON对象） */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleCursorListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    ArticleController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 文章 Slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponseDto"];
                };
            };
            /** @description 文章不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeSessionResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    AuthController_revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutAllResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_findAll: {
        parameters: {
            query?: {
                /** @description 搜索关键词（匹配名称或邮箱） */
                search?: string;
                /** @description 按角色筛选 */
                role?: string;
                /** @description 按封禁状态筛选 */
                banned?: boolean;
                /** @description 页码（从1开始） */
                page?: number;
                /** @description 每页数量 */
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 邮箱已被使用 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    UserController_assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description 权限不足 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 用户不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    DashboardController_getStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                /** @description 客户端生成的 UUID，用于防止重复下单 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description 幂等重放（响应头含 Idempotent-Replayed: true） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description 订单创建成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description 相同 Idempotency-Key 但请求 body 不同 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    OrderController_pay: {
        parameters: {
            query?: never;
            header: {
                "if-match": string;
                /** @description ETag 版本号（来自 GET /orders/:id 响应头），格式: "<number>" */
                "If-Match": string;
            };
            path: {
                /** @description 订单 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 支付成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description 订单不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 订单已支付 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 版本冲突（其他请求已修改订单） */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 缺少 If-Match 请求头 */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    OrderController_ship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 订单 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 发货请求已接受，使用 Location 头中的 URL 轮询任务状态 */
            202: {
                headers: {
                    /**
                     * @description 任务状态查询 URL
                     * @example /api/jobs/550e8400-...
                     */
                    Location?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipOrderResponseDto"];
                };
            };
            /** @description 订单状态不允许发货 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 订单不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    OrderController_bulkCancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCancelDto"];
            };
        };
        responses: {
            /** @description 全部取消成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCancelResponseDto"];
                };
            };
            /** @description 部分成功（含单项错误详情） */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkCancelResponseDto"];
                };
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    OrderController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 订单 ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    /**
                     * @description 版本号，用于乐观锁
                     * @example "0"
                     */
                    ETag?: unknown;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
            /** @description 订单不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
    JobController_findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 任务 ID（来自 202 响应的 Location 头） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponseDto"];
                };
            };
            /** @description 任务不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 错误响应（包括 400/401/403/404/422/429/500 等） */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetailsDto"];
                };
            };
        };
    };
}
