/**
 * Type declaration for CLI Plugin-generated metadata
 *
 * metadata.ts is auto-generated by the @nestjs/swagger CLI Plugin.
 */
declare const metadata: () => Promise<Record<string, unknown>>
export default metadata
