import { base, react, unicorn } from '@infra-x/code-quality/lint'
import { defineConfig } from 'oxlint'

export default defineConfig({
  extends: [base(), unicorn(), react()],
  overrides: [
    {
      // SVGs are auto-generated by @svgr/cli into PascalCase files matching the React component name.
      files: ['src/icons/**/*.tsx'],
      rules: {
        'unicorn/filename-case': 'off',
      },
    },
  ],
})
